### ISSUE TITLE
Numerical instability

### ISSUE THREAD

**Issue by ealonsogzl** [ealonsogzl/MuSA#19]
Hi @krisaalstad,

I have done some tests and AdaMuPBS works very well. But I think we underestimated the small numerical problem that can emerge from here:

https://github.com/ealonsogzl/MuSA/blob/754b36194dca88ff27c0550189fdd77fe65c7ff9/modules/filters.py#L1193

It appears from time to time when playing with the hyper-parameters `Neffthrs`, `ensemble_members` etc..., and not only with very low `r_cov`. Could you take a look?

thanks!

**Comment by krisaalstad** [comment]
@ealonsogzl I will have a look at this in September, thanks for the nice hacking session yesterday!

**Comment by krisaalstad** [comment]
Ok, it was easier to fix than I thought. It was about how "clipping" is done and that we didn't revert to a (scaled version of) the prior covariance matrix for the proposal in cases of severe degeneracy. See the new PR

**Comment by ealonsogzl** [comment]
great, thanks for the PR. 
Regarding your comment, I will do a few tests to see which is more computationally efficient, a large ensemble with a low Neffthrs (probably less iterations) or in the other way around, keeping in mind at least 10 survivors.
