### ISSUE TITLE
yml and pd.downcast

### ISSUE THREAD

**Issue by krisaalstad** [ealonsogzl/MuSA#8]
To test the latest additions, I cloned the latest version of the MuSA repo. In this exericse, I encountered two minor issues:

1) Unlike what it says in the README.md the file used to create the MuSA conda environment is called "MuSA.yml" not "MuSA_env.yml". I guess this could easily be fixed (just rename the file or update the README).
2) Even after creating the environment, one package was missing, namely "pandas downcast" (in modules/internal_fns,py : "import pdcast as pd"). After some searching it was of course possible to acquire this package form pip (https://pypi.org/project/pandas-downcast/), but it would be great if this was also in the .yml file to make the setup even easier.

Cheers,
Kris

**Comment by ealonsogzl** [comment]
I will change the README.md. Right, downcast..., I included it recently to reduce the variable types to the maximum, saving a lot of space automatically.

Thank you!

**Comment by ealonsogzl** [comment]
Done
